apiVersion: v1
kind: Service
metadata:
  name: crud-backend-service
spec:
  type: NodePort
  selector:
    app: crud-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 8088 